api_platform:
    title: 'BileMo REST API'
    description: 'A REST API for BileMo'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
