api_platform:
    title: 'BileMo REST API'
    description: 'A REST API for BileMo'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    http_cache:
        public: true
    defaults:
        cache_header:
            etag: true
            max_age: 3600
            shared_max_age: 3600
            vary: [ 'Content-Type', 'Authorization' ]
